- name: Check out the Redmine source code
  become: yes
  subversion:
    repo={{ redmine_svn_url }}
    dest={{ redmine_dir }}

- name: Create database.yml
  become: yes
  template:
    src=database.yml
    dest={{ redmine_dir }}/config/database.yml
    force=no
  register:
    result_database_yml

- name: Create configuration.yml
  become: yes
  template:
    src=configuration.yml
    dest={{ redmine_dir }}/config/configuration.yml
    force=yes

- name: Check if Gemfile.lock exists
  command:
    test -f {{ redmine_dir }}/Gemfile.lock
  register:
    result_test_gemfile
  failed_when: result_test_gemfile.rc not in [0, 1]
  changed_when: false

- name: Installing the gems package
  become: yes
  command:
    bundle install --path vendor/bundle --without development test
    chdir={{ redmine_dir }}
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
  when:
    result_test_gemfile.rc == 1

- name: Gems package update
  become: yes
  command:
    bundle update
    chdir={{ redmine_dir }}
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
  when:
    result_test_gemfile.rc == 0

- name: Create secret token
  become: yes
  command:
    bundle exec rake generate_secret_token
    chdir={{ redmine_dir }}
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
    RAILS_ENV: production

- name: Database migration
  become: yes
  command:
    bundle exec rake db:migrate
    chdir={{ redmine_dir }}
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
    RAILS_ENV: production

- name: Clear cache
  become: yes
  command:
    bundle exec rake tmp:cache:clear tmp:sockets:clear
    chdir={{ redmine_dir }}
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
    RAILS_ENV: production

- name:  Load default data
  become: yes
  command:
    bundle exec rake redmine:load_default_data
    chdir={{ redmine_dir }}
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
    RAILS_ENV: production
    REDMINE_LANG: "{{ redmine_lang }}"
  when:
    result_database_yml is changed

- name: Change default language
  become: yes
  command:
    bundle exec rails r 'Setting["default_language"]="{{ redmine_lang }}"'
    chdir={{ redmine_dir }}
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
    RAILS_ENV: production
  when:
    result_database_yml is changed

- name: Change display format of user name to "Surname name"
  become: yes
  command:
    bundle exec rails r 'Setting["user_format"]=:lastname_firstname'
    chdir={{ redmine_dir }}
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
    RAILS_ENV: production
  when:
    result_database_yml is changed

- name: Set attachment and repository encoding
  become: yes
  command:
    bundle exec rails r 'Setting["repositories_encodings"]="{{ redmine_repositories_encodings }}"'
    chdir={{ redmine_dir }}
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
    RAILS_ENV: production
  when:
    result_database_yml is changed

- name: Display thumbnail of attached file
  become: yes
  command:
    bundle exec rails r 'Setting["thumbnails_enabled"]="1"'
    chdir={{ redmine_dir }}
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
    RAILS_ENV: production
  when:
    result_database_yml is changed
