- name: Locale creation
  become: yes
  command:
    locale-gen {{ db_locale }}

- name: apt-get update
  become: yes
  apt:
    update_cache=yes
    cache_valid_time=86400

- name: Install python3-psycopg2 for Python3 as we change ansible_python_interpreter=/usr/bin/python3
  become: yes
  apt:
    name: python3-psycopg2

- name: Install development tools and header files necessary for building Ruby and Passenger
  become: yes
  apt:
    name='build-essential,zlib1g-dev,libssl-dev,libreadline-dev,libyaml-dev,libcurl4-openssl-dev'

- name:  Install zip
  become: yes
  apt:
    name='zip,unzip'

- name:  Install ImageMagick and header files & specific fonts
  become: yes
  apt:
    name='imagemagick,libmagick++-dev'

- name:  Install other tools
  become: yes
  apt:
    name='subversion,git'

- name: Create working directory
  file: path={{ work_dir }} state=directory mode=0755
