- name:  PostgreSQL and header file installation
  become: yes
  apt:
    pkg:
    - postgresql
    - postgresql-server-dev-10

- name: User created by PostgreSQL
  become: yes
  become_user: postgres
  postgresql_user:
    name={{ db_user_redmine }}
    password={{ db_passwd_redmine }}

- name: PostgreSQL database creation
  become: yes
  become_user: postgres
  postgresql_db:
    name={{ db_name_redmine }}
    encoding='UTF-8'
    lc_collate={{ db_locale }}
    lc_ctype={{ db_locale }}
    template='template0'
