production:
  email_delivery:
    delivery_method: :smtp
  smtp_settings:
    enable_starttls_auto: true
    ssl: true
    address: "{{ ssmtp_mailhub }}"
    port: "{{ ssmtp_mailport | int }}"
    domain: "{{ ssmtp_hostname}}"
    authentication: :login
    user_name: "{{ ssmtp_user }}" 
    password: "{{ ssmtp_auth_password }}"